default_proxy_apps:
  tk-multi-about:
    location: {name: tk-multi-about, type: app_store, version: v0.1.19}
  tk-multi-screeningroom: '@launch_screeningroom'
  tk-multi-workfiles:
    allow_task_creation: true
    file_extensions: []
    hook_copy_file: default
    hook_filter_publishes: default
    hook_filter_work_files: default
    hook_scene_operation: default
    launch_at_startup: false
    launch_change_work_area_at_startup: false
    location: {name: tk-multi-workfiles, type: app_store, version: v0.5.5}
    saveas_default_name: scene
    saveas_prefer_version_up: false
    sg_entity_type_extra_display_fields: {}
    sg_entity_type_filters: {}
    sg_entity_types: [Shot, Asset]
    task_extra_display_fields: []
    template_publish: null
    template_publish_area: null
    template_work: null
    template_work_area: null
frameworks:
  tk-framework-qtwidgets_v1.x.x:
    location: {name: tk-framework-qtwidgets, type: app_store, version: v1.0.0}
  tk-framework-shotgunutils_v2.x.x:
    location: {name: tk-framework-shotgunutils, type: app_store, version: v2.0.4}
  tk-framework-widget_v0.1.12:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.12}
  tk-framework-widget_v0.1.13:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.13}
  tk-framework-widget_v0.1.15:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.15}
  tk-framework-widget_v0.1.17:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.17}
  tk-framework-widget_v0.1.20:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.20}
  tk-framework-widget_v0.1.23:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.23}
  tk-framework-widget_v0.1.24:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.24}
  tk-framework-widget_v0.2.x:
    location: {name: tk-framework-widget, type: app_store, version: v0.2.0}
include: ./app_launchers.yml
