description: Apps and engines loaded when an Audio is loaded. Since std VFX config
  template has a file system structure which is centered around pipeline steps, this
  environment is largely empty. Most of the work takes place on a level in the file
  system where both an asset and a pipeline step is available - e.g Asset Hero, modeling,
  so all apps for loading, publishing etc. are located in the asset_step environment.
  This environment mostly contains utility apps and the tank work files app, which
  lets you choose a task to work on and load associated content into an application.
engines:
  tk-3dsmax:
    apps: '@default_proxy_apps'
    debug_logging: false
    location: {name: tk-3dsmax, type: app_store, version: v0.3.1}
  tk-maya:
    apps: '@default_proxy_apps'
    compatibility_dialog_min_version: 2015
    debug_logging: false
    location: {name: tk-maya, type: app_store, version: v0.4.2}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    - {app_instance: tk-multi-loader2, name: 0. Full Loader 2.0...}
    template_project: null
    shotPublishPathTemplate: maya_shot_publish
    shotWorkPathTemplate: maya_shot_work
    assetPublishPathTemplate: maya_asset_publish
    assetWorkPathTemplate: maya_asset_work
    use_sgtk_as_menu_name: false
  tk-nuke:
    apps: '@default_proxy_apps'
    compatibility_dialog_min_version: 8
    debug_logging: false
    favourite_directories: []
    location: {name: tk-nuke, type: app_store, version: v0.2.23}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    project_favourite_name: Shotgun Current Project
    use_sgtk_as_menu_name: false
  tk-photoshop:
    apps: '@default_proxy_apps'
    debug_logging: false
    location: {name: tk-photoshop, type: app_store, version: v0.2.0}
  tk-shell:
    apps: {tk-multi-screeningroom: '@launch_screeningroom', tk-shotgun-launch3dsmax: '@launch_3dsmax',
      tk-shotgun-launchmaya: '@launch_maya', tk-shotgun-launchnuke: '@launch_nuke',
      tk-shotgun-launchphotoshop: '@launch_photoshop'}
    debug_logging: false
    location: {name: tk-shell, type: app_store, version: v0.4.0}
    template_project: null
frameworks:
  tk-framework-widget_v0.1.12:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.12}
  tk-framework-widget_v0.1.13:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.13}
  tk-framework-widget_v0.1.15:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.15}
includes: [./includes/app_launchers.yml, ./includes/proxy_apps.yml]
